spring:
  datasource:
    url: jdbc:h2:mem:bddev
    username: hr2023
    password:
  jpa:
    defer-datasource-initialization: true
    show-sql: true
    open-in-view: false
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
  h2:
    console:
      enabled: true
      path: /h2-console
      settings:
        trace: false
        web-allow-others: false
security:
  headers:
    frame: false